// launchd implementation of ServiceManager for macOS targets.
//
// Layout choices:
//   - Service files land in /Library/LaunchDaemons (system-wide,
//     persists across reboots, runs as the configured User). Per-user
//     LaunchAgents would only run when the matching user has a GUI
//     session, which doesn't fit a daemon.
//   - Names are mapped: "okesu-jobs" → com.okesu.jobs.plist;
//     "okesu-agent@edr" → com.okesu.agent.edr.plist. Reverse mapping
//     in ListOkesuAgents reads the plist filenames back.
//   - launchd doesn't natively understand env files, so when an
//     EnvironmentFile is set we wrap ExecStart in `bash -c 'set -a;
//     [[ -r FILE ]] && . FILE; set +a; exec ARGS'` so the file is
//     sourced before the binary runs.
//   - "Install" performs `launchctl bootstrap system /path/to.plist`
//     which both registers and starts the service. "EnableAndStart"
//     is therefore a no-op idempotent check.

package sshdeploy

import (
	"fmt"
	"strings"
)

type launchdManager struct{}

func (launchdManager) Flavour() ServiceFlavour { return FlavourLaunchd }

func (launchdManager) Install(c *Client, sudo string, spec ServiceSpec) error {
	label := launchdLabel(spec.Name)
	plistPath := "/Library/LaunchDaemons/" + label + ".plist"
	plist := renderLaunchdPlist(label, spec)

	if err := writeWithSudo(c, sudo, plistPath, plist, "0644"); err != nil {
		return fmt.Errorf("write %s: %w", plistPath, err)
	}
	if _, err := runWithSudo(c, sudo, "chown root:wheel "+plistPath); err != nil {
		return fmt.Errorf("chown %s: %w", plistPath, err)
	}
	// Bootout first to make this idempotent — re-running an install
	// against an already-loaded plist returns "service already loaded"
	// from bootstrap. Bootout fails harmlessly when the service isn't
	// loaded, so we ignore that error.
	_, _ = runWithSudo(c, sudo, "launchctl bootout system/"+label+" 2>/dev/null || true")
	if out, err := runWithSudo(c, sudo, "launchctl bootstrap system "+plistPath); err != nil {
		return fmt.Errorf("launchctl bootstrap: %w (%s)", err, out)
	}
	return nil
}

// EnableAndStart is a no-op on launchd because Install already
// loaded + started the service. We still verify the service is
// running so the caller catches a configuration error early.
func (launchdManager) EnableAndStart(c *Client, sudo string, name string) error {
	label := launchdLabel(name)
	out, err := runWithSudo(c, sudo, "launchctl print system/"+label+" >/dev/null 2>&1 && echo ok || echo missing")
	if err != nil {
		return fmt.Errorf("verify launchctl print: %w", err)
	}
	if strings.TrimSpace(out) != "ok" {
		return fmt.Errorf("service %s not loaded after bootstrap", label)
	}
	return nil
}

func (launchdManager) Restart(c *Client, sudo string, name string) error {
	label := launchdLabel(name)
	if out, err := runWithSudo(c, sudo, "launchctl kickstart -k system/"+label); err != nil {
		return fmt.Errorf("launchctl kickstart -k %s: %w (%s)", label, err, out)
	}
	return nil
}

func (launchdManager) Stop(c *Client, sudo string, name string) error {
	label := launchdLabel(name)
	if out, err := runWithSudo(c, sudo, "launchctl bootout system/"+label); err != nil {
		return fmt.Errorf("launchctl bootout %s: %w (%s)", label, err, out)
	}
	return nil
}

func (launchdManager) ListOkesuAgents(c *Client) ([]string, error) {
	// New convention: com.okesu.agent-<NAME>.plist (label produced by
	// launchdLabel("okesu-agent-<NAME>")). Old convention with `.` is
	// not generated by this codebase but kept in the matcher for safety.
	out, err := c.Run(`ls /Library/LaunchDaemons 2>/dev/null | awk '/^com\.okesu\.agent[-.]/ && /\.plist$/ {print}'`)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		base := strings.TrimSuffix(line, ".plist")
		var agent string
		switch {
		case strings.HasPrefix(base, "com.okesu.agent-"):
			agent = strings.TrimPrefix(base, "com.okesu.agent-")
		case strings.HasPrefix(base, "com.okesu.agent."):
			agent = strings.TrimPrefix(base, "com.okesu.agent.")
		}
		if agent != "" {
			names = append(names, agent)
		}
	}
	return names, nil
}

// launchdLabel translates a generic ServiceSpec.Name into the
// reverse-DNS form launchd expects. Examples:
//   - "okesu-jobs"        → com.okesu.jobs
//   - "okesu-agent@edr"   → com.okesu.agent.edr
//
// The mapping is symmetric: ListOkesuAgents inverts it.
func launchdLabel(name string) string {
	if strings.HasPrefix(name, "okesu-agent@") {
		return "com.okesu.agent." + strings.TrimPrefix(name, "okesu-agent@")
	}
	if strings.HasPrefix(name, "okesu-") {
		return "com.okesu." + strings.TrimPrefix(name, "okesu-")
	}
	// Fallback: any caller-supplied label is appended verbatim.
	return "com.okesu." + name
}

// renderLaunchdPlist writes a launchd plist body. The file format is
// XML; we keep the layout flat to match Apple's `man launchd.plist`
// recommendations.
//
// Notable choices:
//   - RunAtLoad=true — start immediately when the plist is loaded.
//   - KeepAlive=true with successfulExit=false — restart on failure
//     but not on clean exit, mirroring systemd's Restart=on-failure.
//   - EnvironmentVariables would normally hold static env, but we
//     need *file*-sourced env (so secrets aren't on disk in plain
//     XML), so we wrap ExecStart in a bash invocation that sources
//     the file before exec'ing the binary.
func renderLaunchdPlist(label string, s ServiceSpec) string {
	exec := s.ExecStart
	if s.EnvironmentFile != "" {
		exec = fmt.Sprintf(`bash -c 'set -a; [ -r %q ] && . %q; set +a; exec %s'`, s.EnvironmentFile, s.EnvironmentFile, s.ExecStart)
	}

	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString(`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">` + "\n")
	b.WriteString(`<plist version="1.0">` + "\n")
	b.WriteString("<dict>\n")
	b.WriteString("  <key>Label</key>\n")
	b.WriteString("  <string>" + xmlEscape(label) + "</string>\n")
	b.WriteString("  <key>ProgramArguments</key>\n")
	b.WriteString("  <array>\n")
	b.WriteString("    <string>/bin/sh</string>\n")
	b.WriteString("    <string>-c</string>\n")
	b.WriteString("    <string>" + xmlEscape(exec) + "</string>\n")
	b.WriteString("  </array>\n")
	if s.User != "" {
		b.WriteString("  <key>UserName</key>\n")
		b.WriteString("  <string>" + xmlEscape(s.User) + "</string>\n")
	}
	if s.Group != "" {
		b.WriteString("  <key>GroupName</key>\n")
		b.WriteString("  <string>" + xmlEscape(s.Group) + "</string>\n")
	}
	if s.WorkingDirectory != "" {
		b.WriteString("  <key>WorkingDirectory</key>\n")
		b.WriteString("  <string>" + xmlEscape(s.WorkingDirectory) + "</string>\n")
	}
	b.WriteString("  <key>RunAtLoad</key>\n  <true/>\n")
	b.WriteString("  <key>KeepAlive</key>\n")
	b.WriteString("  <dict>\n    <key>SuccessfulExit</key>\n    <false/>\n  </dict>\n")
	b.WriteString("  <key>StandardOutPath</key>\n  <string>/var/log/okesu/" + xmlEscape(label) + ".out.log</string>\n")
	b.WriteString("  <key>StandardErrorPath</key>\n  <string>/var/log/okesu/" + xmlEscape(label) + ".err.log</string>\n")
	b.WriteString("</dict>\n")
	b.WriteString("</plist>\n")
	return b.String()
}

func xmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;", "'", "&apos;")
	return r.Replace(s)
}
