apiVersion: v1
kind: Service
metadata:
  name: {{ include "okesu-cp.fullname" . }}
  labels:
    {{- include "okesu-cp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: ui
      protocol: TCP
    - name: mgmt
      port: {{ .Values.service.mgmtPort }}
      targetPort: mgmt
      protocol: TCP
  selector:
    {{- include "okesu-cp.selectorLabels" . | nindent 4 }}
